export const socketEventNames = {
  joinRoom: "join_room",
  leaveRoom: "leave_room",
  heartbeat: "heartbeat",
  presenceSnapshot: "presence_snapshot",
  sendChat: "send_chat",
  chatMessage: "chat_message",
  chatRejected: "chat_rejected",
  sendLike: "send_like",
  likeAggregate: "like_aggregate",
  sendGift: "send_gift",
  giftEvent: "gift_event",
  giftRejected: "gift_rejected",
  roomLive: "room_live",
  roomEnded: "room_ended",
  userMuted: "user_muted",
  userKicked: "user_kicked",
  roomChatDisabled: "room_chat_disabled",
  accountRestricted: "account_restricted",
  broadcastHealth: "broadcast_health",
  sessionReady: "session_ready",
  sessionError: "session_error",
} as const;

